# This is a basic workflow to help you get started with Actions

name: test-notebooks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6.9"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: pip install
      run: pip install -r requirements.txt
    - name: Check kerenls
      run: jupyter kernelspec list
    - name: run knn_digits.ipynb
      run: papermill knn_iris.ipynb - -k python
